version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
    environment:
      - REDIS_PASSWORD=redis

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuarios
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
